A panel is a 3D container of data. The term Panel data is derived from econometrics and is partially responsible for the name pandas − pan(el)-da(ta)-s.

The names for the 3 axes are intended to give some semantic meaning to describing operations involving panel data. They are −

    items − axis 0, each item corresponds to a DataFrame contained inside.

    major_axis − axis 1, it is the index (rows) of each of the DataFrames.

    minor_axis − axis 2, it is the columns of each of the DataFrames.
    
    pandas.Panel(data, items, major_axis, minor_axis, dtype, copy)


### Example

In [2]:
# creating an empty panel
import pandas as pd
import numpy as np

data = np.random.rand(2,6,5)
print(data)
p = pd.Panel(data)
print(p)

[[[ 0.51869131  0.32288513  0.53325614  0.9894172   0.42708328]
  [ 0.70150392  0.11208639  0.43596537  0.14450727  0.05862118]
  [ 0.27138573  0.56459957  0.07082793  0.62300985  0.58746552]
  [ 0.80889552  0.25876254  0.17044511  0.20225976  0.4842641 ]
  [ 0.96794238  0.05915531  0.77550611  0.95324787  0.6101206 ]
  [ 0.45138237  0.60402179  0.21397708  0.72811711  0.15291434]]

 [[ 0.94305128  0.22009242  0.67852189  0.85684912  0.95231603]
  [ 0.917492    0.27035155  0.34403277  0.25721487  0.65594109]
  [ 0.00150582  0.55497244  0.62770699  0.65726485  0.93861208]
  [ 0.50202966  0.74035524  0.68099073  0.09074561  0.78820684]
  [ 0.95930837  0.96724968  0.58746615  0.68075649  0.0228308 ]
  [ 0.65193223  0.20763193  0.13746163  0.88551918  0.74716973]]]
<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 6 (major_axis) x 5 (minor_axis)
Items axis: 0 to 1
Major_axis axis: 0 to 5
Minor_axis axis: 0 to 4


In [8]:
#From dict of DataFrame Objects
#creating an empty panel

import pandas as pd
import numpy as np

data = {'Item1' : pd.DataFrame(np.random.randn(5, 6)), 
        'Item2' : pd.DataFrame(np.random.randn(5, 7))}

print(data)
print("\n")
p = pd.Panel(data)
print(p)

{'Item1':           0         1         2         3         4         5
0 -0.974394 -0.242364 -0.876109  0.003586  0.701751 -0.403967
1 -0.059584  0.979180 -0.063190  0.908342  0.411148 -0.866321
2 -0.919357 -2.643367  0.671855 -1.152068 -1.824000 -0.129111
3 -1.971417 -0.491467 -0.445279  1.041668 -0.013366  0.915126
4  1.414006  0.464044 -0.434745 -0.436013 -0.700476  0.975768, 'Item2':           0         1         2         3         4         5         6
0 -0.938769  0.570110 -0.206545  0.678206  1.090052  2.663934 -0.007153
1 -0.286763 -1.162049  0.273651 -0.817655  1.082408  1.216307  0.410705
2 -0.193216 -0.181595 -0.486881  0.941400  0.021934 -0.490895 -0.420290
3  0.268560  0.440370  0.520213 -2.376982 -1.084017 -0.750436 -0.357933
4 -0.027551  1.017986  0.171597 -0.532228  0.378057  0.189504  0.684860}


<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 5 (major_axis) x 7 (minor_axis)
Items axis: Item1 to Item2
Major_axis axis: 0 to 4
Minor_axis axis: 0 to 6


In [9]:
#An empty panel can be created using the Panel constructor as follows −

#creating an empty panel
import pandas as pd
p = pd.Panel()
print(p)

<class 'pandas.core.panel.Panel'>
Dimensions: 0 (items) x 0 (major_axis) x 0 (minor_axis)
Items axis: None
Major_axis axis: None
Minor_axis axis: None


In [10]:
#Data can be accessed using the method panel.major_axis(index).

# creating an empty panel
import pandas as pd
import numpy as np
data = {'Item1' : pd.DataFrame(np.random.randn(4, 3)), 
        'Item2' : pd.DataFrame(np.random.randn(4, 2))}
p = pd.Panel(data)
print(p.major_xs(3))

      Item1     Item2
0 -0.597147  0.869612
1  0.542089 -0.448738
2 -1.331090       NaN


In [11]:
#Using minor_axis

#Data can be accessed using the method panel.minor_axis(index).

# creating an empty panel
import pandas as pd
import numpy as np
data = {'Item1' : pd.DataFrame(np.random.randn(4, 3)), 
        'Item2' : pd.DataFrame(np.random.randn(4, 2))}
p = pd.Panel(data)
print (p.minor_xs(0))

      Item1     Item2
0 -0.335564 -0.319336
1  0.172743 -1.115110
2 -0.444918  1.707177
3 -1.647715 -2.295055
