# Linear algebra

In [1]:
import numpy as np

In [2]:
np.__version__

'1.13.3'

## Matrix and vector products

Q1. Predict the results of the following code.

In [4]:
x = [1,2]
y = [[4, 1], [2, 2]]
print (np.dot(x, y))
print (np.dot(y, x))
print (np.matmul(x, y))
print (np.inner(x, y))
print (np.inner(y, x))

[8 5]
[6 6]
[8 5]
[6 6]
[6 6]


Q2. Predict the results of the following code.

In [5]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
print (np.dot(y, x))
print(np.matmul(y, x))


[[4 1]
 [2 2]
 [1 1]]
[[4 1]
 [2 2]
 [1 1]]


Q3. Predict the results of the following code.

In [6]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
print (np.vdot(x, y))
print (np.vdot(y, x))
print (np.dot(x.flatten(), y.flatten()))
print (np.inner(x.flatten(), y.flatten()))
print ((x*y).sum())

30
30
30
30
30


Q4. Predict the results of the following code.

In [6]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
print(np.inner(x, y))
print(np.inner(y, x))
print (np.outer(x, y))
print (np.outer(y, x))

abb
abb
[['a' 'aa']
 ['b' 'bb']]
[['a' 'b']
 ['aa' 'bb']]


## Decompositions

Q5. Get the lower-trianglular `L` in the Cholesky decomposition of x and verify it.

In [7]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
L = np.linalg.cholesky(x)
print (L)
assert(np.array_equal(np.dot(L, L.T.conjugate()), x))

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


Q6. Compute the qr factorization of x and verify it.

In [8]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
q, r = np.linalg.qr(x)
print ("q=\n", q, "\nr=\n", r)
assert (np.allclose(np.dot(q, r), x))

q=
 [[-0.85714287  0.39428571  0.33142856]
 [-0.42857143 -0.90285712 -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]] 
r=
 [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


Q7. Factor x by Singular Value Decomposition and verify it.

In [9]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
U, s, V = np.linalg.svd(x, full_matrices=False)
print ("U=\n", U, "\ns=\n", s, "\nV=\n", V)
assert (np.allclose(np.dot(U, np.dot(np.diag(s), V)), x))


U=
 [[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]] 
s=
 [ 3.          2.23606801  2.          0.        ] 
V=
 [[-0.          0.          1.          0.          0.        ]
 [ 0.44721359  0.          0.          0.          0.89442718]
 [-0.          1.          0.          0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]]


## Norms  numbers

Q10. Calculate the Frobenius norm and the condition number of x.

In [10]:
x = np.arange(1, 10).reshape((3, 3))
print(np.linalg.norm(x, 'fro'))


16.8819430161
